
# This script draws a simple triangle or any shape using print statements
print("   /|")
print("  / |")
print(" /  |")
print("/___|")
print("")
print("")
print("      *")
print("     *")
print("    *")
print("   *")
print("  *")
print("*")
print("  *")
print("   *")
print("    *")
print("     *")
print("      *")